// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM1SLweqrV-fdofEsExKBVqBzYKqhVgHQ',
    appId: '1:741167316123:web:a6178b819eacc269c55a3e',
    messagingSenderId: '741167316123',
    projectId: 'finca-152a7',
    authDomain: 'finca-152a7.firebaseapp.com',
    storageBucket: 'finca-152a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9XBFDTlHxfgXr07z8XvAvmybQhSVFwK8',
    appId: '1:741167316123:android:92475fe0771c9105c55a3e',
    messagingSenderId: '741167316123',
    projectId: 'finca-152a7',
    storageBucket: 'finca-152a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz6kAUNCwxhPK-e_YkS-sRP9hZyk_GC3s',
    appId: '1:741167316123:ios:5c352d8db8ab39abc55a3e',
    messagingSenderId: '741167316123',
    projectId: 'finca-152a7',
    storageBucket: 'finca-152a7.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz6kAUNCwxhPK-e_YkS-sRP9hZyk_GC3s',
    appId: '1:741167316123:ios:a448e529a64182a7c55a3e',
    messagingSenderId: '741167316123',
    projectId: 'finca-152a7',
    storageBucket: 'finca-152a7.appspot.com',
    iosBundleId: 'com.example.flutterApp.RunnerTests',
  );
}
